import sys
import os
import torch
import torch.nn.functional as F
from blt.byte_encoder import UTF8Encoder
from blt.config import GlobalConfig
from blt.blt_model import ByteLatentTransformer


def main():
    # 1. Device Setup (prefer MPS/CUDA for speed)
    if torch.backends.mps.is_available():
        device = torch.device("mps")
    elif torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")
    print(f"Using device: {device}\n")

    # 2. Load Checkpoint
    checkpoint_path = "blt_checkpoint.pt"
    if not os.path.exists(checkpoint_path):
        print(f"Error: Checkpoint '{checkpoint_path}' not found. Please train the model first by running 'python train.py'.")
        return

    print(f"Loading checkpoint from {checkpoint_path}...")
    checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
    config = checkpoint["config"]
    
    # Initialize and load weights
    model = ByteLatentTransformer(config)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.to(device)
    model.eval()
    print("Model loaded successfully.")

    # 3. Prompt and Generation Settings
    prompt = "No more"
    max_new_bytes = 150
    temperature = 0.8
    greedy = False  # Now uses Top-K sampling

    print(f"\nPrompt: '{prompt}'")
    print("Generating: ", end="")
    sys.stdout.flush()

    # Convert prompt to byte IDs
    byte_ids = UTF8Encoder.encode(prompt).to(device)

    # 4. Generation Loop (Byte-by-Byte)
    with torch.no_grad():
        for _ in range(max_new_bytes):
            # Limit sequence length to block_size if necessary
            input_seq = byte_ids[-config.block_size :]
            
            # Forward pass
            logits = model(input_seq)  # [1, seq_len, 256]
            
            # Get logits at the last position
            next_byte_logits = logits[0, -1, :]
            
            if greedy:
                next_byte = torch.argmax(next_byte_logits).item()
            else:
                # Apply temperature scaling
                logits = next_byte_logits / max(1e-5, temperature)
                
                # Top-K filtering
                top_k = 10
                v, _ = torch.topk(logits, min(top_k, logits.size(-1)))
                logits[logits < v[[-1]]] = -float('Inf')
                
                probs = F.softmax(logits, dim=-1)
                next_byte = torch.multinomial(probs, num_samples=1).item()
            
            # Append generated byte to sequence
            byte_ids = torch.cat([byte_ids, torch.tensor([next_byte], device=device)])
            
            # Print the generated byte immediately
            try:
                char = bytes([next_byte]).decode("utf-8", errors="replace")
                sys.stdout.write(char)
                sys.stdout.flush()
            except Exception:
                pass
                
    print("\n\nGeneration complete!")


if __name__ == "__main__":
    main()
